collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'src/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      # - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime' }
      - { label: 'Revision Date', name: 'updatedDate', widget: 'datetime' }
      - { label: 'Featured Image', name: 'heroImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
